### ISSUE TITLE
Issues with python35

### ISSUE THREAD

**Issue by ivvv** [telegraphic/fits2hdf#11]
Got the latest fro github, tried to install. Then tried to import the module and it failed with an error: cannot find module idi

Copied idi.py to the lib/python3.5/site-packages folder (i.e. one up from fits2hdf) and this time it went OK, but it failed again for missing import of ordereddict. pip installed it.

Then it failed again for missing import of UserDict. No success with pip or Conda as it seem that UserDict is not ported to python 3.5. 

These dependencies, ordereddict and UserDict, are not mentioned. I guess they are coming from idi.py.

I hope this helps debug the code. I was planning to try it out, just to see if I could use it for some Herschel data. But it seems that either I have to install a new python 2.7 environment and try it again or wait for fixes for python 3.5.

**Comment by telegraphic** [comment]
Hi @ivvv, 

Currently there is only support for python 2.7. Among other things, `h5py` handles attributes differently in Python 3 (see https://github.com/h5py/h5py/issues/379), so it's probably not all that straightforward. Python 3 support would be great though, so I'll leave this issue open.

**Comment by mrawls** [comment]
+1 for Python 3 support! I fixed(?) the `ordereddict` dependency by importing OrderedDict from `collections` instead, but even with this change and `idi.py` in the site-packages folder (one up from fits2hdf, as @ivvv mentioned), more/deeper issues remain.

**Comment by telegraphic** [comment]
Closing this one and #8. As we now have Py3 support
