### ISSUE TITLE
fits2hdf project maintenance

### ISSUE THREAD

**Issue by EiffL** [telegraphic/fits2hdf#18]
Hi @telegraphic 
Thanks a lot for putting this package together, it's incredibly useful, and a shame more people are not using it. Can I ask what's the  maintenance status of this repo?
Do you need extra help for doing bug fixes, and maintaining a PyPi page, or even push forward  an integration into astropy?

**Comment by telegraphic** [comment]
Hey @EiffL, it'd be wonderful to have maintenance help, and I'm open to enhancements and suggestions that can foster usability. Other projects have taken a lot of my free cycles (I'm looking at you, [hickle](https://github.com/telegraphic/hickle)) -- activity on the repo and seeing usage would certainly motivate keeping this well-maintained :)

**Comment by EiffL** [comment]
Great :-) Happy to help! No pressure but feel free to add me as an extra collaborator/maintainer if  you want.
Could I just bother you with pushing the project to PyPi?  So that you would be the owner of the project. Then I'm happy to help with maintaining it, and setup automated pushes to PyPi.

**Comment by telegraphic** [comment]
Sounds GTM, will do it today while I have momentum

**Comment by telegraphic** [comment]
Ok, we have a v1.1.1 -- https://pypi.org/project/fits2hdf/

Thanks a heap for the big push forward and for future bugfixes!

**Comment by EiffL** [comment]
Fantastic! Thanks a lot!
I'll advertise the package to my community, hopefully this will bring in a few new users.
And I think that pretty much closes this issue :-D
