### ISSUE TITLE
Support for round-tripping

### ISSUE THREAD

**Issue by keflavich** [telegraphic/fits2hdf#2]
Following on #1, I'd be interested in using `fits2hdf`, but only if there is a way to return to FITS, ideally preserving all metadata.  Even if HDF5 is not adopted by reduction tools - and I don't expect it to be any time soon - I think it could be a useful data transport format if there's a way to load it into current visualization and reduction tools.

**Comment by telegraphic** [comment]
Hi @keflavich -- agreed that round-tripping is important, I'm hoping to implement this soon. I'll respond on this thread once there's a `hdf2fits` utility.

If you're interested, the main work will be writing an `export_fits` function in fitsio.py:
https://github.com/telegraphic/fits2hdf/blob/master/fits2hdf/io/fitsio.py

As Tim pointed out in #1, there will likely be complications that make creating output files which are identical to input files more difficult (e.g. checksums, binary vs. ascii table output, etc).

**Comment by telegraphic** [comment]
Finally getting back to this! I've added in capability to return to FITS, so "round tripping" is now possible, but the round-tripped file will not be identical. The main reason for this is that I couldn't find an acceptable solution that wasn't a poor HDF5 implementation for the data model port. I can now direct you to the newly accepted [HDFITS paper](http://www.sciencedirect.com/science/article/pii/S2213133715000554) for more discussion (section 4.1):

```
D.C. Price, B.R. Barsdell, L.J. Greenhill, HDFITS: Porting the FITS data model to HDF5,
Astronomy and Computing, Available online 22 May 2015, ISSN 2213-1337,
http://dx.doi.org/10.1016/j.ascom.2015.05.001.
```

Have a look at Section 6.4 for a quick trick to get HDF5 into existing python data reduction / viewer tools. The first person to abstract the file access away from the data model in CFITSIO wins a puppy.

I'm going to close this issue now, but feel free to continue discussion / reopen if you wanna continue the dialog.
