### ISSUE TITLE
Install command line scripts

### ISSUE THREAD

**Issue by cdeil** [telegraphic/fits2hdf#5]
It would be convenient if `pythons setup.py install` installed the command line scripts.

The recommended way to do this is with setuptools entry_points:
https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation
http://astropy.readthedocs.org/en/latest/development/scripts.html

**Comment by telegraphic** [comment]
Thanks & agreed, I've marked it as an enhancement and will put it on the todo list.

**Comment by telegraphic** [comment]
This probably motivates moving to `argparse` from `optparse`, so will have to do that first. Looks relatively straightforward after that.

**Comment by telegraphic** [comment]
OK, seems to be working. I probably need to do a bit more testing as it's the first time I've used entry points, but looking good.

**Comment by cdeil** [comment]
@telegraphic – Thanks!

Is it useful to keep the top-level scripts in the repo?
I don't think it's common to do this for Python packages that have command line scripts, and generally it's bad to give users two ways to do the same thing?

**Comment by telegraphic** [comment]
Looks like I did remove the top-level scripts at some stage, so closing this one too.
