### ISSUE TITLE
Tests and travis-ci

### ISSUE THREAD

**Issue by cdeil** [telegraphic/fits2hdf#7]
How do you run the tests? Simply `py.test-2.7` from the top-level folder?

It's usually better to move the tests into the package so that they can also be run with an installed package, i.e. as a user "am I doing something wrong or is the install broken"?

Also, could you please activate travis-ci for this repo?

I'd be happy to make a PR with a `.travis.yml` file and moves the `test` folder into the package, but first #6 should be decided / fixed, currently the tests don't pass for me: https://gist.github.com/cdeil/df57d231fcf65a28e083

**Comment by telegraphic** [comment]
Admittedly the test framework is basic at the moment. Have just activated travis-ci; I'm away from office this week but will get this working asap.

**Comment by telegraphic** [comment]
tests should now run using `py.test` from the ./test/ directory. I'll need to make some changes so that the tests can be run from the root path

**Comment by telegraphic** [comment]
Four years later, #17 by @EiffL has set up travis-CI 🚀

**Comment by telegraphic** [comment]
Closing
