### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by cdeil** [telegraphic/fits2hdf#8]
It would be nice if `fits2hdf` worked with Python 3 (it's my main Python install and users are starting to shift, see [here](http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/)).

I had a quick look ... I think making this work with Python 3 is trivial, it's mostly `print` and imports need to be adapted (no implicit relative imports and import *)
I can make a PR, but first #6 and #7 should be done.

**Comment by telegraphic** [comment]
Yes, Py3 support is probably an important thing to focus on. An underlying issue is h5py / Python 3, as [discussed here](https://github.com/h5py/h5py/issues/379), but it looks like in a worst case scenario we could do custom error handling.

**Comment by cdeil** [comment]
@telegraphic – Yes, strings are a huge pain if you want to support Python 2 / 3 and HDF5 or FITS. The core issue is in Numpy. But there's tons of data without string columns, so how to handle this can be discussed / implemented later, no?

**Comment by telegraphic** [comment]
#17 adds Py3 support! Thanks @EiffL. Closing this one (1529 days later)
